### ISSUE TITLE
Missing methods

### ISSUE THREAD

**Issue by dtex** [rwaldron/imp-io#12]
Add i2cConfig(), i2cWrite(), i2cRead() and i2cReadOnce methods because Johnny-Five expects those now.

**Comment by dtex** [comment]
I've got this in my fork. Coming soon.

**Comment by rwaldron** [comment]
'bout time

;)

**Comment by dtex** [comment]
Ya, I completely forgot it wasn't finished. My personal plate (as opposed to my business plate) is pretty clean so I'm going to focus on this. I forgot how complicated this was. Going to try and improve the comments as I "re-learn" it.

**Comment by BrianGenisio** [comment]
Noticed the J5 website claims support for I2C: http://johnny-five.io/platform-support/#electric-imp-april

**Comment by dtex** [comment]
I submitted a PR to update the website. I've got I2C working but it's not ready for release.

**Comment by rwaldron** [comment]
Yeah, that was a little overly optimistic of me.
